name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: |
          npm run test -- --coverage || true

      - name: Upload coverage to SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -D"sonar.organization=Abdul Kayum Muslim" \
            -D"sonar.projectKey=Integrate-SonarQube-with-GitHub-Actions-for-Code-Quality-Analysis" \
            -D"sonar.sources=." \
            -D"sonar.exclusions=node_modules/**" \
            -D"sonar.javascript.lcov.reportPaths=coverage/lcov.info" \
            -D"sonar.login=$SONAR_TOKEN"

